# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ip_dns_telemetry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ip_dns_telemetry.proto\x12\x08wc.stats\"\x87\x02\n\rWCHealthStats\x12\x14\n\x0ctotalLookups\x18\x01 \x01(\r\x12\x11\n\tcacheHits\x18\x02 \x01(\r\x12\x15\n\rremoteLookups\x18\x03 \x01(\r\x12\x1c\n\x14\x63onnectivityFailures\x18\x04 \x01(\r\x12\x17\n\x0fserviceFailures\x18\x05 \x01(\r\x12\x15\n\runcategorized\x18\x06 \x01(\r\x12\x12\n\nminLatency\x18\x07 \x01(\r\x12\x12\n\nmaxLatency\x18\x08 \x01(\r\x12\x16\n\x0e\x61verageLatency\x18\t \x01(\r\x12\x15\n\rcachedEntries\x18\n \x01(\r\x12\x11\n\tcacheSize\x18\x0b \x01(\r\".\n\x0bWCRiskStats\x12\x0c\n\x04risk\x18\x01 \x01(\x05\x12\x11\n\ttotalHits\x18\x02 \x01(\r\"Q\n\x0fWCCategoryStats\x12\x12\n\ncategoryId\x18\x01 \x01(\x05\x12*\n\x0bwcRiskStats\x18\x02 \x03(\x0b\x32\x15.wc.stats.WCRiskStats\"g\n\x0bWCRuleStats\x12\x12\n\npolicyName\x18\x01 \x01(\t\x12\x10\n\x08ruleName\x18\x02 \x01(\t\x12\x32\n\x0fwcCategoryStats\x18\x03 \x03(\x0b\x32\x19.wc.stats.WCCategoryStats\"I\n\x0bWCHeroStats\x12\x0e\n\x06srcMac\x18\x01 \x02(\t\x12*\n\x0bwcRuleStats\x18\x02 \x03(\x0b\x32\x15.wc.stats.WCRuleStats\"6\n\x10ObservationPoint\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x12\n\nlocationId\x18\x02 \x01(\t\"7\n\x11ObservationWindow\x12\x11\n\tstartedAt\x18\x01 \x01(\x04\x12\x0f\n\x07\x65ndedAt\x18\x02 \x01(\x04\"\xed\x01\n\rWCStatsReport\x12\x12\n\nwcProvider\x18\x01 \x01(\t\x12\x34\n\x10observationPoint\x18\x02 \x01(\x0b\x32\x1a.wc.stats.ObservationPoint\x12\x36\n\x11observationWindow\x18\x03 \x01(\x0b\x32\x1b.wc.stats.ObservationWindow\x12.\n\rwcHealthStats\x18\x04 \x01(\x0b\x32\x17.wc.stats.WCHealthStats\x12*\n\x0bwcHeroStats\x18\x05 \x03(\x0b\x32\x15.wc.stats.WCHeroStats')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ip_dns_telemetry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WCHEALTHSTATS._serialized_start=37
  _WCHEALTHSTATS._serialized_end=300
  _WCRISKSTATS._serialized_start=302
  _WCRISKSTATS._serialized_end=348
  _WCCATEGORYSTATS._serialized_start=350
  _WCCATEGORYSTATS._serialized_end=431
  _WCRULESTATS._serialized_start=433
  _WCRULESTATS._serialized_end=536
  _WCHEROSTATS._serialized_start=538
  _WCHEROSTATS._serialized_end=611
  _OBSERVATIONPOINT._serialized_start=613
  _OBSERVATIONPOINT._serialized_end=667
  _OBSERVATIONWINDOW._serialized_start=669
  _OBSERVATIONWINDOW._serialized_end=724
  _WCSTATSREPORT._serialized_start=727
  _WCSTATSREPORT._serialized_end=964
# @@protoc_insertion_point(module_scope)
