# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: latency.proto
# Protobuf Python Version: 4.25.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlatency.proto\x12\x07latency\"q\n\x06Sample\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x04\x12\x0e\n\x06min_ms\x18\x02 \x01(\r\x12\x0e\n\x06max_ms\x18\x03 \x01(\r\x12\x0e\n\x06\x61vg_ms\x18\x04 \x01(\r\x12\x0f\n\x07last_ms\x18\x05 \x01(\r\x12\x10\n\x08num_pkts\x18\x06 \x01(\r\"\xaf\x01\n\x04Host\x12\x0f\n\x07if_name\x18\x01 \x01(\t\x12\x13\n\x0bmac_address\x18\x02 \x01(\x0c\x12$\n\tdscp_type\x18\x03 \x01(\x0e\x32\x11.latency.DscpType\x12\x12\n\ndscp_value\x18\x04 \x01(\r\x12\x0f\n\x07if_role\x18\x07 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x05 \x02(\x04\x12 \n\x07samples\x18\x06 \x03(\x0b\x32\x0f.latency.Sample\"7\n\x06Report\x12\x0f\n\x07node_id\x18\x01 \x02(\t\x12\x1c\n\x05hosts\x18\x02 \x03(\x0b\x32\r.latency.Host*$\n\x08\x44scpType\x12\x0b\n\x07PRESENT\x10\x00\x12\x0b\n\x07MISSING\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'latency_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DSCPTYPE']._serialized_start=376
  _globals['_DSCPTYPE']._serialized_end=412
  _globals['_SAMPLE']._serialized_start=26
  _globals['_SAMPLE']._serialized_end=139
  _globals['_HOST']._serialized_start=142
  _globals['_HOST']._serialized_end=317
  _globals['_REPORT']._serialized_start=319
  _globals['_REPORT']._serialized_end=374
# @@protoc_insertion_point(module_scope)
