# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_manager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14object_manager.proto\x12\x15object_manager.status\"9\n\x11observation_point\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0blocation_id\x18\x02 \x01(\t\">\n\robject_status\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\xad\x01\n\x14object_status_report\x12\x13\n\x0breported_at\x18\x01 \x01(\x04\x12\x43\n\x11observation_point\x18\x02 \x01(\x0b\x32(.object_manager.status.observation_point\x12;\n\robject_status\x18\x03 \x03(\x0b\x32$.object_manager.status.object_status')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_manager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBSERVATION_POINT._serialized_start=47
  _OBSERVATION_POINT._serialized_end=104
  _OBJECT_STATUS._serialized_start=106
  _OBJECT_STATUS._serialized_end=168
  _OBJECT_STATUS_REPORT._serialized_start=171
  _OBJECT_STATUS_REPORT._serialized_end=344
# @@protoc_insertion_point(module_scope)
