# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opensync_nflog.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14opensync_nflog.proto\"\x91\x03\n\x05nflog\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0blocation_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\x0f\n\x07hw_addr\x18\x04 \x01(\t\x12\x0f\n\x07\x66w_mark\x18\x05 \x01(\r\x12\x16\n\x0eingress_ifname\x18\x06 \x01(\t\x12\x15\n\regress_ifname\x18\x07 \x01(\t\x12\x19\n\x11ingress_phyifname\x18\x08 \x01(\t\x12\x18\n\x10\x65gress_phyifname\x18\t \x01(\t\x12\x0e\n\x06prefix\x18\n \x01(\t\x12\x13\n\x0bnl_group_id\x18\x0b \x01(\x05\x12\x0f\n\x07payload\x18\x0c \x01(\x0c\x12\x0e\n\x06hwtype\x18\r \x01(\r\x12\r\n\x05hwlen\x18\x0e \x01(\r\x12\x10\n\x08hwheader\x18\x0f \x01(\x0c\x12\x16\n\x0eingress_ifrole\x18\x10 \x01(\t\x12\x15\n\regress_ifrole\x18\x11 \x01(\t\x12\x19\n\x11ingress_phyifrole\x18\x12 \x01(\t\x12\x18\n\x10\x65gress_phyifrole\x18\x13 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opensync_nflog_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NFLOG']._serialized_start=25
  _globals['_NFLOG']._serialized_end=426
# @@protoc_insertion_point(module_scope)
