# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thread_network_info.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19thread_network_info.proto\x12\x04otbr\"8\n\x10ObservationPoint\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0blocation_id\x18\x02 \x01(\t\"\xe2\x01\n\rThreadNetwork\x12\x10\n\x08\x65xt_addr\x18\x01 \x01(\x06\x12\x12\n\next_pan_id\x18\x02 \x01(\x06\x12\x0e\n\x06pan_id\x18\x03 \x01(\r\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x15\n\rsteering_data\x18\x05 \x01(\x0c\x12\x0f\n\x07\x63hannel\x18\x06 \x01(\r\x12\x0c\n\x04rssi\x18\x07 \x01(\x05\x12\x0b\n\x03lqi\x18\x08 \x01(\r\x12\x17\n\x0fjoiner_udp_port\x18\t \x01(\r\x12\x0f\n\x07version\x18\n \x01(\r\x12\x0e\n\x06native\x18\x0b \x01(\x08\x12\x10\n\x08\x64iscover\x18\x0c \x01(\x08\"m\n\x11ThreadNetworkScan\x12%\n\x08networks\x18\x01 \x03(\x0b\x32\x13.otbr.ThreadNetwork\x12\x31\n\x11observation_point\x18\x02 \x01(\x0b\x32\x16.otbr.ObservationPointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thread_network_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBSERVATIONPOINT']._serialized_start=35
  _globals['_OBSERVATIONPOINT']._serialized_end=91
  _globals['_THREADNETWORK']._serialized_start=94
  _globals['_THREADNETWORK']._serialized_end=320
  _globals['_THREADNETWORKSCAN']._serialized_start=322
  _globals['_THREADNETWORKSCAN']._serialized_end=431
# @@protoc_insertion_point(module_scope)
