# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10time_event.proto\x12\x03sts\"a\n\tTimeEvent\x12\x0c\n\x04time\x18\x01 \x02(\x04\x12\x0b\n\x03\x63\x61t\x18\x03 \x02(\t\x12\x0e\n\x06source\x18\x04 \x02(\t\x12\x0f\n\x07subject\x18\x05 \x01(\t\x12\x0b\n\x03seq\x18\x06 \x01(\t\x12\x0b\n\x03msg\x18\x07 \x01(\t\"J\n\x08\x44\x65viceID\x12\x0f\n\x07node_id\x18\x01 \x02(\t\x12\x18\n\x10\x66irmware_version\x18\x02 \x02(\t\x12\x13\n\x0blocation_id\x18\x03 \x02(\t\"\x86\x01\n\x10TimeEventsReport\x12\x1f\n\x08\x64\x65viceID\x18\x01 \x02(\x0b\x32\r.sts.DeviceID\x12\r\n\x05seqNo\x18\x02 \x02(\r\x12\x10\n\x08realTime\x18\x03 \x02(\x04\x12\x10\n\x08monoTime\x18\x04 \x02(\x04\x12\x1e\n\x06\x65vents\x18\x05 \x03(\x0b\x32\x0e.sts.TimeEvent')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEEVENT._serialized_start=25
  _TIMEEVENT._serialized_end=122
  _DEVICEID._serialized_start=124
  _DEVICEID._serialized_end=198
  _TIMEEVENTSREPORT._serialized_start=201
  _TIMEEVENTSREPORT._serialized_end=335
# @@protoc_insertion_point(module_scope)
