# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upnp_portmap.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12upnp_portmap.proto\x12\x0cupnp.portmap\"\xfc\x01\n\x07Portmap\x12+\n\x06source\x18\x01 \x01(\x0e\x32\x1b.upnp.portmap.CaptureSource\x12\x16\n\x0e\x63\x61ptured_at_ms\x18\x02 \x01(\x04\x12\x11\n\tdevice_id\x18\x03 \x01(\x0c\x12)\n\x08protocol\x18\x04 \x01(\x0e\x32\x17.upnp.portmap.Protocols\x12\x10\n\x08\x65xt_port\x18\x05 \x01(\r\x12\x12\n\nint_client\x18\x06 \x01(\r\x12\x10\n\x08int_port\x18\x07 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\t\x12\x0f\n\x07\x65nabled\x18\t \x01(\t\x12\x10\n\x08\x64uration\x18\n \x01(\x05\"8\n\x10ObservationPoint\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0blocation_id\x18\x02 \x01(\t\"\x84\x01\n\x06Report\x12\x16\n\x0ereported_at_ms\x18\x02 \x01(\x04\x12\x39\n\x11observation_point\x18\x01 \x01(\x0b\x32\x1e.upnp.portmap.ObservationPoint\x12\'\n\x08portmaps\x18\x03 \x03(\x0b\x32\x15.upnp.portmap.Portmap*7\n\tProtocols\x12\x18\n\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x07\n\x03TCP\x10\x01\x12\x07\n\x03UDP\x10\x02*\x7f\n\rCaptureSource\x12\x1e\n\x1a\x43\x41PTURE_SOURCE_UNSPECIFIED\x10\x00\x12\x0c\n\x08IGD_POLL\x10\x01\x12\x10\n\x0cOVSDB_STATIC\x10\x02\x12\x16\n\x12PKT_INSPECTION_ADD\x10\x03\x12\x16\n\x12PKT_INSPECTION_DEL\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upnp_portmap_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOCOLS._serialized_start=484
  _PROTOCOLS._serialized_end=539
  _CAPTURESOURCE._serialized_start=541
  _CAPTURESOURCE._serialized_end=668
  _PORTMAP._serialized_start=37
  _PORTMAP._serialized_end=289
  _OBSERVATIONPOINT._serialized_start=291
  _OBSERVATIONPOINT._serialized_end=347
  _REPORT._serialized_start=350
  _REPORT._serialized_end=482
# @@protoc_insertion_point(module_scope)
