#!/bin/bash

DCONF_DIR=~/.cache/dconf/
# Check ownership of DCONF_DIR as firefox requires user permission
[ -d $DCONF_DIR ] && [ $(stat -c %U $DCONF_DIR) = "root" ] && \
    echo -e "Change owner for directory $DCONF_DIR\nsudo chown -R $USER:$USER ~/.cache/dconf/"

if [[ $# -ge 1 ]]; then
  REPORT_PATH=$1
else
  REPORT_PATH=/tmp/automation/allure-results/report
fi

firefox "$REPORT_PATH/index.html"
