#!/usr/bin/env python3
"""
Convert a Pipfile.lock file, received via stdin, to full-featured requirements.txt file, on stdout.

Pipfile develop packages are currently ignored.
"""

import json
import platform
import sys


def main(argv):
    """
    `Pipenv requirements` omits lots of fields when converting Pipfile.lock, so we need to convert it manually.
    """
    if argv[1:]:
        print(__doc__, file=sys.stderr)
        return
    js = json.load(sys.stdin)
    on_rpi = platform.processor() == "armv7l"
    if on_rpi:
        print("--extra-index-url=https://www.piwheels.org/simple")
    for package, info in js.get("default", {}).items():
        requirement = [package]
        requirement.append(info.get("version", ""))
        if "markers" in info:
            requirement.append("; ")
            requirement.append(info["markers"])
        # Skip hash-checking on RPI, because it disables locally-built wheel cache, and
        # most of our binary package dependencies on RPI don't have prebuilt wheels. See
        # https://pip.pypa.io/en/stable/topics/secure-installs/#interaction-with-caching
        # for details.
        if not on_rpi:
            for checksum in info.get("hashes", []):
                requirement.append(" \\\n    --hash=")
                requirement.append(checksum)
        print("".join(requirement))


if __name__ == "__main__":
    main(sys.argv)
