#!/usr/bin/env bash

OPENSYNC_ROOT=$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")


PROMPT='
  cyan=$(tput setaf 6)
  green=$(tput setaf 2)
  blue=$(tput setaf 4)
  bold=$(tput bold)
  reset=$(tput sgr0)
  PS1="\[$bold\]\[$cyan\][$OPENSYNC_TESTBED]\[$green\]\u@\h:\[$blue\]\w\[$reset\]\$ "
'
show_tools()
{
    echo
    source_dir="$(dirname ${BASH_SOURCE[0]})"
    osrt testbed tools
    echo
}

list_testbeds()
{
    skip_files="Jenkinsfile README.md _testbed_pools.yaml _testbed_reserve_exclude.txt"
    local test_beds=$(for i in $OPENSYNC_ROOT/config/locations/*; do
      echo $skip_files | grep -w -q $(basename $i)
      if [[ $? -eq 0 ]]; then
        continue
      fi
      echo $(basename $i) | sed -e 's/.yaml//g';
      done)
    echo
    echo "========================="
    echo "== Configured testbeds =="
    echo "========================="
    echo
    echo "$test_beds" | ( tty <&1 >/dev/null && column || cat )
    echo
}

prun()
{
    if [[ -n "$OPENSYNC_TESTBED" ]]; then
        echo "OPENSYNC_TESTBED=$OPENSYNC_TESTBED"
        if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
            show_tools
            echo "Testbed environment is running in a sub-shell. To leave it, use 'exit'."
            echo; echo
            exit
        else
            echo
            echo "OPENSYNC_TESTBED is set, please first deactivate with 'exit'!"
            echo
            exit 1
        fi
    fi

    if [[ -e /.dockerenv ]]; then
        if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
            list_testbeds && show_tools

            echo "Most of the tools require a testbed to be selected via the 'osrt shell' command. To select a testbed, run:"
            echo "    osrt shell <testbed_name>"
            echo "A testbed environment runs in a sub-shell. To leave it, use:"
            echo "    exit"
            echo "To run a single command on a testbed, use:"
            echo "    osrt run <testbed_name> -- <command> [<parameters>]"
            echo; echo

            exit
        fi

        # HFS+ macOS filesystem usually is configured to be case insensitive. That's why we can't use "-f" option
        if [[ $(ls $OPENSYNC_ROOT/config/locations/ | grep $1.yaml) ]]; then
            export OPENSYNC_TESTBED=$1
            if [[ -z ${PROMPT_COMMAND} ]]; then
                export PROMPT_COMMAND=${PROMPT}
            else
                export debian_chroot="testbed:$OPENSYNC_TESTBED"
            fi
            if [[ $# -eq 1 ]]; then
              cache-tb-config $1 || true
              osrt testbed tools
              osrt shell $OPENSYNC_TESTBED
            else
              shift
              osrt run $OPENSYNC_TESTBED -- "$@"
            fi
        else
            echo "Configuration for location $1 not found."
            return 1
        fi
        return
    fi

    if [[ -f $OPENSYNC_ROOT/config/locations/$1.yaml ]]; then
        export OPENSYNC_TESTBED=$1
        echo "Activating environment for $OPENSYNC_TESTBED"
        cd $OPENSYNC_ROOT
        . $OPENSYNC_ROOT/.venv/bin/pactivate
        testbed tools
        osrt shell $OPENSYNC_TESTBED
        cd - > /dev/null
    else
        echo "Configuration for location $1 not found."
        return 1
    fi
}

prun "$@"
